name: Compilar APK (Buildozer)

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

run-name: Compilacion Android
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Configurar dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip install --upgrade buildozer cython

    - name: Compilar APK con Buildozer
      run: buildozer android debug

    - name: Subir APK generado
      uses: actions/upload-artifact@v4
      with:
        name: BlockBlastAI-Bot
        path: bin/*.apk
